name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
            - uses: actions/checkout@v2
            - name: Run django unit tests
            run:
                pip3 install --user django
                python3 manage.py test
